### ISSUE TITLE
bug: Obstacles don't release after End Level Position

### ISSUE THREAD

**Issue by pavlo-klymentenko-legacy** [StansAssets/com.stansassets.running-dinosaur-clone#6]
![image](https://user-images.githubusercontent.com/13795723/118356288-2585d780-b57d-11eb-8c94-6265658dad4c.png)
This is an example of a bug. Cactus on the left should be released into a pool already, but it doesn't.
Please fix it ASAP!!!

**Comment by AlexUA93** [comment]
![image](https://user-images.githubusercontent.com/75200600/118396198-aeb90f00-b64e-11eb-90b2-b5b86e97cd92.png)
I change 13 and 15 line in ObjectSpawner.
13 line before: [SerializeField] RectTransform m_backToPoolPosition;
13 line after: [SerializeField] GameObject m_backToPoolPosition;
15 line before: int ReleasePositionX => (int)m_backToPoolPosition.anchoredPosition.x;
15 line after: int ReleasePositionX => (int)m_backToPoolPosition.transform.position.x;
